// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr31Mf4p5bRY6aFWc5YYxB83U1CHVR7pg',
    appId: '1:349990404274:web:1ee01c069308b07cc2c9ab',
    messagingSenderId: '349990404274',
    projectId: 'ecommerceapp-9e234',
    authDomain: 'ecommerceapp-9e234.firebaseapp.com',
    storageBucket: 'ecommerceapp-9e234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5hVeU9-4X0Tuaxliyl1LlD4k-I0BCMVQ',
    appId: '1:349990404274:android:bdc0cf53b0460241c2c9ab',
    messagingSenderId: '349990404274',
    projectId: 'ecommerceapp-9e234',
    storageBucket: 'ecommerceapp-9e234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHKwjOeHa2RRuFGFnuXSv68im4geAhn5I',
    appId: '1:349990404274:ios:5f1a2add4bb5f41ec2c9ab',
    messagingSenderId: '349990404274',
    projectId: 'ecommerceapp-9e234',
    storageBucket: 'ecommerceapp-9e234.appspot.com',
    androidClientId: '349990404274-0b7ouvrbspn3f35ms0uhh24b3ohltlmt.apps.googleusercontent.com',
    iosClientId: '349990404274-cib765vdce7g0t975189u2fqgp2h554t.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}